name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.11"] # min and max supported versions?
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        # Install deps as root since we will run tests as root
        scripts/ci-install-deps.sh
        pip install -vvv --no-binary :all: .
    - run: python -c 'import pkg_resources; print(pkg_resources.require("input-remapper"))'
    - run: python -c 'import pkg_resources; print(pkg_resources.require("input-remapper")[0].location)'
    - name: Run tests
      run: |
        # FIXME: Had some permissions issues, currently worked around by running tests as root
        mkdir test_tmp
        TMPDIR="$(realpath test_tmp)" python tests/test.py --start-dir unit
