name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.11"] # min and max supported versions?
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        # Install deps as root since we will run tests as root
        scripts/ci-install-deps.sh
        sudo pip install -vvv --prefix=~/.local/ --no-binary :all:
    - run: python -c 'import pkg_resources; print(pkg_resources.require("input-remapper"))'
    - run: python -c 'import pkg_resources; print(pkg_resources.require("input-remapper")[0].location)'
    - run: ls -R /opt/hostedtoolcache/Python/${{ matrix.python-version }}*/x64/lib/python${{ matrix.python-version }}/site-packages/usr/share/input-remapper
    - run: ls -R /home/runner/work/input-remapper/input-remapper
    - run: find / -name input-remapper 2> /dev/null
      continue-on-error: true
    - run: find . -name input-remapper 2> /dev/null
      continue-on-error: true
    - name: Run tests
      run: |
        # FIXME: Had some permissions issues, currently worked around by running tests as root
        mkdir test_tmp
        TMPDIR="$(realpath test_tmp)" python tests/test.py --start-dir unit
